/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.umn.cs.mapreduce;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum JobStatus implements org.apache.thrift.TEnum {
  SUCCESS(0),
  NO_FILES_IN_INPUT_DIR(1),
  NO_NODES_IN_CLUSTER(2);

  private final int value;

  private JobStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JobStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return SUCCESS;
      case 1:
        return NO_FILES_IN_INPUT_DIR;
      case 2:
        return NO_NODES_IN_CLUSTER;
      default:
        return null;
    }
  }
}
