/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.umn.cs.mapreduce;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-04-21")
public class SortResponse implements org.apache.thrift.TBase<SortResponse, SortResponse._Fields>, java.io.Serializable, Cloneable, Comparable<SortResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SortResponse");

  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField INTERMEDIATE_FILE_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("intermediateFilePath", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField EXECUTION_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("executionTime", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SortResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SortResponseTupleSchemeFactory());
  }

  /**
   * 
   * @see Status
   */
  public Status status; // required
  public String intermediateFilePath; // optional
  public long executionTime; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see Status
     */
    STATUS((short)1, "status"),
    INTERMEDIATE_FILE_PATH((short)2, "intermediateFilePath"),
    EXECUTION_TIME((short)3, "executionTime");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STATUS
          return STATUS;
        case 2: // INTERMEDIATE_FILE_PATH
          return INTERMEDIATE_FILE_PATH;
        case 3: // EXECUTION_TIME
          return EXECUTION_TIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __EXECUTIONTIME_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.INTERMEDIATE_FILE_PATH,_Fields.EXECUTION_TIME};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, Status.class)));
    tmpMap.put(_Fields.INTERMEDIATE_FILE_PATH, new org.apache.thrift.meta_data.FieldMetaData("intermediateFilePath", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EXECUTION_TIME, new org.apache.thrift.meta_data.FieldMetaData("executionTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SortResponse.class, metaDataMap);
  }

  public SortResponse() {
  }

  public SortResponse(
    Status status)
  {
    this();
    this.status = status;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SortResponse(SortResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetStatus()) {
      this.status = other.status;
    }
    if (other.isSetIntermediateFilePath()) {
      this.intermediateFilePath = other.intermediateFilePath;
    }
    this.executionTime = other.executionTime;
  }

  public SortResponse deepCopy() {
    return new SortResponse(this);
  }

  @Override
  public void clear() {
    this.status = null;
    this.intermediateFilePath = null;
    setExecutionTimeIsSet(false);
    this.executionTime = 0;
  }

  /**
   * 
   * @see Status
   */
  public Status getStatus() {
    return this.status;
  }

  /**
   * 
   * @see Status
   */
  public SortResponse setStatus(Status status) {
    this.status = status;
    return this;
  }

  public void unsetStatus() {
    this.status = null;
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return this.status != null;
  }

  public void setStatusIsSet(boolean value) {
    if (!value) {
      this.status = null;
    }
  }

  public String getIntermediateFilePath() {
    return this.intermediateFilePath;
  }

  public SortResponse setIntermediateFilePath(String intermediateFilePath) {
    this.intermediateFilePath = intermediateFilePath;
    return this;
  }

  public void unsetIntermediateFilePath() {
    this.intermediateFilePath = null;
  }

  /** Returns true if field intermediateFilePath is set (has been assigned a value) and false otherwise */
  public boolean isSetIntermediateFilePath() {
    return this.intermediateFilePath != null;
  }

  public void setIntermediateFilePathIsSet(boolean value) {
    if (!value) {
      this.intermediateFilePath = null;
    }
  }

  public long getExecutionTime() {
    return this.executionTime;
  }

  public SortResponse setExecutionTime(long executionTime) {
    this.executionTime = executionTime;
    setExecutionTimeIsSet(true);
    return this;
  }

  public void unsetExecutionTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __EXECUTIONTIME_ISSET_ID);
  }

  /** Returns true if field executionTime is set (has been assigned a value) and false otherwise */
  public boolean isSetExecutionTime() {
    return EncodingUtils.testBit(__isset_bitfield, __EXECUTIONTIME_ISSET_ID);
  }

  public void setExecutionTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __EXECUTIONTIME_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((Status)value);
      }
      break;

    case INTERMEDIATE_FILE_PATH:
      if (value == null) {
        unsetIntermediateFilePath();
      } else {
        setIntermediateFilePath((String)value);
      }
      break;

    case EXECUTION_TIME:
      if (value == null) {
        unsetExecutionTime();
      } else {
        setExecutionTime((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STATUS:
      return getStatus();

    case INTERMEDIATE_FILE_PATH:
      return getIntermediateFilePath();

    case EXECUTION_TIME:
      return getExecutionTime();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STATUS:
      return isSetStatus();
    case INTERMEDIATE_FILE_PATH:
      return isSetIntermediateFilePath();
    case EXECUTION_TIME:
      return isSetExecutionTime();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SortResponse)
      return this.equals((SortResponse)that);
    return false;
  }

  public boolean equals(SortResponse that) {
    if (that == null)
      return false;

    boolean this_present_status = true && this.isSetStatus();
    boolean that_present_status = true && that.isSetStatus();
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (!this.status.equals(that.status))
        return false;
    }

    boolean this_present_intermediateFilePath = true && this.isSetIntermediateFilePath();
    boolean that_present_intermediateFilePath = true && that.isSetIntermediateFilePath();
    if (this_present_intermediateFilePath || that_present_intermediateFilePath) {
      if (!(this_present_intermediateFilePath && that_present_intermediateFilePath))
        return false;
      if (!this.intermediateFilePath.equals(that.intermediateFilePath))
        return false;
    }

    boolean this_present_executionTime = true && this.isSetExecutionTime();
    boolean that_present_executionTime = true && that.isSetExecutionTime();
    if (this_present_executionTime || that_present_executionTime) {
      if (!(this_present_executionTime && that_present_executionTime))
        return false;
      if (this.executionTime != that.executionTime)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_status = true && (isSetStatus());
    list.add(present_status);
    if (present_status)
      list.add(status.getValue());

    boolean present_intermediateFilePath = true && (isSetIntermediateFilePath());
    list.add(present_intermediateFilePath);
    if (present_intermediateFilePath)
      list.add(intermediateFilePath);

    boolean present_executionTime = true && (isSetExecutionTime());
    list.add(present_executionTime);
    if (present_executionTime)
      list.add(executionTime);

    return list.hashCode();
  }

  @Override
  public int compareTo(SortResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIntermediateFilePath()).compareTo(other.isSetIntermediateFilePath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIntermediateFilePath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.intermediateFilePath, other.intermediateFilePath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetExecutionTime()).compareTo(other.isSetExecutionTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExecutionTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.executionTime, other.executionTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SortResponse(");
    boolean first = true;

    sb.append("status:");
    if (this.status == null) {
      sb.append("null");
    } else {
      sb.append(this.status);
    }
    first = false;
    if (isSetIntermediateFilePath()) {
      if (!first) sb.append(", ");
      sb.append("intermediateFilePath:");
      if (this.intermediateFilePath == null) {
        sb.append("null");
      } else {
        sb.append(this.intermediateFilePath);
      }
      first = false;
    }
    if (isSetExecutionTime()) {
      if (!first) sb.append(", ");
      sb.append("executionTime:");
      sb.append(this.executionTime);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (status == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'status' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SortResponseStandardSchemeFactory implements SchemeFactory {
    public SortResponseStandardScheme getScheme() {
      return new SortResponseStandardScheme();
    }
  }

  private static class SortResponseStandardScheme extends StandardScheme<SortResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SortResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status = edu.umn.cs.mapreduce.Status.findByValue(iprot.readI32());
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // INTERMEDIATE_FILE_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.intermediateFilePath = iprot.readString();
              struct.setIntermediateFilePathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // EXECUTION_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.executionTime = iprot.readI64();
              struct.setExecutionTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SortResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.status != null) {
        oprot.writeFieldBegin(STATUS_FIELD_DESC);
        oprot.writeI32(struct.status.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.intermediateFilePath != null) {
        if (struct.isSetIntermediateFilePath()) {
          oprot.writeFieldBegin(INTERMEDIATE_FILE_PATH_FIELD_DESC);
          oprot.writeString(struct.intermediateFilePath);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetExecutionTime()) {
        oprot.writeFieldBegin(EXECUTION_TIME_FIELD_DESC);
        oprot.writeI64(struct.executionTime);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SortResponseTupleSchemeFactory implements SchemeFactory {
    public SortResponseTupleScheme getScheme() {
      return new SortResponseTupleScheme();
    }
  }

  private static class SortResponseTupleScheme extends TupleScheme<SortResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SortResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.status.getValue());
      BitSet optionals = new BitSet();
      if (struct.isSetIntermediateFilePath()) {
        optionals.set(0);
      }
      if (struct.isSetExecutionTime()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetIntermediateFilePath()) {
        oprot.writeString(struct.intermediateFilePath);
      }
      if (struct.isSetExecutionTime()) {
        oprot.writeI64(struct.executionTime);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SortResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.status = edu.umn.cs.mapreduce.Status.findByValue(iprot.readI32());
      struct.setStatusIsSet(true);
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.intermediateFilePath = iprot.readString();
        struct.setIntermediateFilePathIsSet(true);
      }
      if (incoming.get(1)) {
        struct.executionTime = iprot.readI64();
        struct.setExecutionTimeIsSet(true);
      }
    }
  }

}

